"""empty message

Revision ID: 41413a101417
Revises: d057f8a39f44
Create Date: 2021-03-25 14:38:45.192768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41413a101417'
down_revision = 'd057f8a39f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
